version: "3.7"
services:
  app:
    image: local/cep:test
    build:
      context: ./
      target: dev
      args:
        NODE_ENV: development
    command: >
      /bin/ash -c "
        npm test
      "
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
