version: '3.6'
services:
  test:
    build:
      context: ./
      args:
        NODE_ENV: test
        PORT: ${PORT:-3000}
    image: cep:test
    container_name: test
    command: ["npm", "test"]
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/home/node/app/lib
      - ./test:/home/node/app/test
