version: '3'
services:
  test:
    build:
      context: ./
      args:
        npm_cmd: "npm i --progress=false --quiet"
    command: ["npm", "test"]
    environment:
      - NODE_ENV=test
    volumes:
      - ./test:/home/node/lib/test

## to run
# docker-compose -f docker-compose.test.yml run test

## to build
# docker-compose -f docker-compose.test.yml up --build -d
