version: '3.4'
services:
  test:
    build:
      context: ./
      args:
        npm_cmd: "npm i --progress=false --quiet"
    image: cep:test
    command: ["npm", "test"]
    environment:
      - NODE_ENV=test
    volumes:
      - ./test:/home/node/app/test
