version: '3.7'
services:
  app:
    build:
      context: ./
      args:
        NODE_ENV: development
    image: local/cep:test
    command: ["npm", "test"]
    volumes:
      - ./src:/home/node/app/src
      - ./test:/home/node/app/test
